---
version: "3.4"
services:
  nodejs:
    image: node
    environment:
      PORT: "3000"
    ports:
      - "3000:3000"
    working_dir: /opt/node/nautobot
    user: node
    volumes:
      - ../nautobot_ui/:/opt/node/nautobot
      - ../:/source
    command: >
      bash -c "npm install && npm run build && npm run start"
  nautobot:
    command: nautobot-server ourrunserver 0.0.0.0:8080 --insecure
