---
version: "3.4"
services:
  nautobot:
    depends_on:
      - db
  db:
    image: postgres:13
    env_file:
      - dev.env
    volumes:
      - pgdata_nautobot:/var/lib/postgresql/data
volumes:
  pgdata_nautobot:
