---
version: "3.4"
services:
  nodejs:
    image: node
    environment:
      PORT: "3000"
    ports:
      - "3000:3000"
    working_dir: /opt/node/nautobot
    volumes:
      - ../frontend-next/:/opt/node/nautobot
    command: npm run dev
  nautobot:
    command: nautobot-server start --http :8080 --master --processes 3 --threads 2 --buffer-size 32768
