---
version: "3.4"
services:
  nodejs:
    image: node
    environment:
      PORT: "8888"
    working_dir: /opt/node/nautobot
    volumes:
      - ../frontend-next/:/opt/node/nautobot
    command: npm run dev
  nginx:
    image: nginx
    ports:
      - "8888:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../nautobot/project-static/:/opt/nautobot/static/
  nautobot:
    command: nautobot-server start --http :8080 --socket :8081 --master --processes 3 --threads 2 --buffer-size 32768
