---
version: "3.4"
services:
  nodejs:
    image: node
    environment:
      PORT: "3000"
    ports:
      - "3000:3000"
    working_dir: /opt/node/nautobot
    volumes:
      - ../nautobot_ui/:/opt/node/nautobot
      - nautobot_ui_nodemodules:/opt/node/nautobot/node_modules
    command: >
      bash -c "npm install && npm run start"
  nautobot:
    command: nautobot-server start --http :8080 --master --processes 3 --threads 2 --buffer-size 32768
volumes:
  nautobot_ui_nodemodules:
